### ISSUE TITLE
Things to complete before releasing xarray v0.9.0

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1167]
- [x] Add drop=True argument to isel, sel and squeeze #1153
- [x] Add `set_index`, `reset_index` and `reorder_levels` methods #1028
- [x] Variable.copy() should copy dask.arrays #1166
- [x] Switch to shared Lock (SerializableLock if possible) for reading/writing #1179

@pydata/xarray anything else essential?

**Comment by MaximilianR** [comment]
Are we pushing https://github.com/pydata/xarray/pull/964? This would be awesome to start working on, although important to get right given it'll be a platform

**Comment by shoyer** [comment]
I also really want to merge #964 (the "apply" function) but the current API is a little too confusing. We could merge it without exposing it as public API for now and/or start building simplified versions (e.g., with an optional `dim` argument instead of `signature`).

I agree that it should be a top priority but I don't want to let it hold up 0.9 any longer, so I think we should release without it. `apply` does not change any APIs in a breaking way so we can even both put it in a minor release if desried (though obviously it is a big feature).

**Comment by jhamman** [comment]
I have two smaller features I'd like to get in:

- [ ] Unlimited dimensions / `Dataset.encoding` #1170 
- [ ] `Dataset.info` method #1176 

These are both pretty close and could be wrapped up in a day or so.

**Comment by shoyer** [comment]
What's our status here? I'd like to get the release (maybe a release candidate) out this week if possible.

It would be great if someone else could take a look at #1166 and #1179.

**Comment by shoyer** [comment]
There is never an ideal time to make a release cut, but this has been dragging on for too long. I just sent out an email announcing a release candidate for v0.9.0:
https://groups.google.com/forum/#!topic/xarray/Yc6A45zXmwM

Unlimited dimensions will have to wait to the v0.9.1 release, but that release can follow pretty shortly given that the changes should be mostly backwards compatible.

**Comment by ghisvail** [comment]
@shoyer Do you plan to push a release tarball for `0.9.0rc1` on PyPI? I'd prefer to use this version over `0.8.2` as the basis for the initial Debian packaging. I tested both and found `0.9.0rc1` to lead to less errors with the test suite than `0.8.2`. I could also wait for `0.9.0` final if its release is planned soon.

**Comment by shoyer** [comment]
@ghisvail Oops, I forgot to upload the source distribution to pypi (now fixed).

The final release should be some time this week, up to you if you want to wait.

**Comment by ghisvail** [comment]
> The final release should be some time this week, up to you if you want to wait.

Thanks @shoyer, I used the rc to try out the packaging and give you some initial feedback. See #1208 and #1209.

**Comment by fmaussion** [comment]
If I wrap up this thread, I see we are missing:

- [ ] https://github.com/pydata/xarray/pull/1170 (Unlimited dimensions / Dataset.encoding)
- [ ] https://github.com/pydata/xarray/pull/1222 (testing module)
- [ ] https://github.com/pydata/xarray/pull/1221 (document the repr)

**Comment by shoyer** [comment]
With the merge of #1222, I plan to issue the new release tonight or tomorrow morning (pending a successful doc build and a final check-over).

**Comment by fmaussion** [comment]
It is picky but it might be worth to pin mpl to v2 for nicer plots in the docs ;-) Am I allowed to try it out?

**Comment by shoyer** [comment]
Certainly, give it a try!

**Comment by rabernat** [comment]
Not that this matters greatly to xarray, but I am happy to report that the latest master causes no problems with [xmitgcm](http://github/xgcm/xmitgcm), which, because of the custom DataStore, is a somewhat obscure edge case. Full speed ahead with the release!

**Comment by shoyer** [comment]
@rabernat the DataStore refactor will happen sometime soon I hope, but I will definitely coordinate with you!

**Comment by jhamman** [comment]
@shoyer - glad this is coming together. Let me know if you'd like any help with the release steps.

**Comment by fmaussion** [comment]
@shoyer I've tested mpl on the ``fix-docs`` branch and they seem to build properly (see the [dashboard](https://readthedocs.org/projects/xray/builds/)), but for some reason xarray's webpage is unreachable right now so I can't see how it looks like. It's getting late here in central europe so if you want to make the release later today go ahead, MPL2 can wait.

**Comment by shoyer** [comment]
The built docs look pretty good to me, so I think we can go ahead with
matplotlib 2.0: http://xarray.pydata.org/en/fix-docs/plotting.html

**Comment by pwolfram** [comment]
I think we can close this because 0.9.0 has been released.
