### ISSUE TITLE
Checklist for v0.2 release

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#183]
Requirements:
- [x] Better documentation:
  - [x] Tutorial introduces `DataArray` before and independently of `Dataset`
  - [x] Revise README to emphasize that xray generalizes pandas to N-dimensions
  - [x] New FAQ section to clarify relationship of xray to pandas, Iris and CDAT (#112)
  - [x] Update What's New
- [x] More consistent names:
  - [x] `dimensions` -> `dims` and `coordinates` -> `coords` (#190)
  - [x] `noncoordinates` -> `noncoords`
- [x] Lay groundwork for non-index coordinates (#197):
  - [x] Require specifying `attrs` with a keyword argument in `Dataset.__init__` (to make room for `coords`)
  - [x] Don't allow indexing `array.coords[0]`
  - [x] Remove the `to` argument from `Dataset.apply` (it will be much less clearly useful when we have non-index coords)
  - [x] Add warning in the docs (clarify that "linked dataset variables" are going away)

Nice to have:
- [x] Support modifying DataArray dimensions/coordinates in place (#180)
- [ ] Automatic alignment in mathematical operations (#184)
- [ ] Revised interface for CF encoding/decoding (#155, #175)
