### ISSUE TITLE
0.10.2 release

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1975]
In the spirit of our goal for a more rapid release (https://github.com/pydata/xarray/issues/1821), let's aim to issue the 0.10.2 release in the next few days, ideally after the following PRs are merged (all of which are nearly ready):

- [x] fix distributed writes #1793
- [x] einsum for xarray #1968
- [x] Support __array_ufunc__ for xarray objects. #1962

CC @pydata/xarray

**Comment by shoyer** [comment]
all these are merged, now, so I'll probably issue the release on my commute home tonight.

**Comment by shoyer** [comment]
I tagged the release and uploaded to pypi. ReadTheDocs is currently building the docs and a pull request for updating conda-forge is up for review: https://github.com/conda-forge/xarray-feedstock/pull/29

**Comment by jhamman** [comment]
Thanks @shoyer!
