### ISSUE TITLE
v0.10.5 release

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#2182]
We had several regressions in v0.10.4, so I'd like to issue a v0.10.5 release shortly with some fixes.

I also had a couple of highly productive plane rides to/from vacation, so I found time to put together a number of bug-fix PRs. If anyone has time to help review these, it would be greatly appreciated!

Issues to resolve:
- ~~How should Dataset.update() handle conflicting coordinates?~~ #2180 (resolved for now)

PRs for regressions in v0.10.4:
- [x] Fix writing to groups with h5netcdf #2181
- [x] Fix DataArray.stack() with non-unique coordinates on pandas 0.23 #2168
- [x] Fix dtype=S1 encoding in to_netcdf() #2158

PRs for older bugs:
- [x] Fix DataArray.groupby().reduce() mutating input array #2169
- [x] Bug fixes for Dataset.reduce() and n-dimensional cumsum/cumprod #2156
- [x] Validate output dimension sizes with apply_ufunc #2155 
- [x] Fix string slice indexing for a length-1 CFTimeIndex #2166
- [x] Fix unlimited dims bug #2154

cc @pydata/xarray @crusaderky

**Comment by shoyer** [comment]
OK, that took a little longer than I thought!

I plan to merge https://github.com/pydata/xarray/pull/2158/ and issue the 0.10.5 end of day today unless anyone has objections.

**Comment by shoyer** [comment]
I tagged v0.10.5 and uploaded it to pypi before noticing that due to a bug in our versioneer setup, our version number was `v0.10.5` instead of the correct `0.10.5`. Oops!

Pypi doesn't allow overwriting files, so I just tagged and uploaded v0.10.6 as well.

Hopefully this version builds properly on conda-forge: https://github.com/conda-forge/xarray-feedstock/pull/33
