### ISSUE TITLE
0.12.2 release

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#2977]
Seems like we're close to a release with some nice features. The following PRs are either done or are really close:

Features:

- [ ] #1597 stack/unstacking for ML
- [x] #2556 transpose_coords
- [x] #2616 ND combine
- [x] #2964 fill_value for concat / combine
- [ ] #2277 dataset plotting needs a review. 

indexes:

- [ ] #2816 
- [x] #2859 consistency checks

Bugfixes:

- [x] #2207 chunksizes
- [x] #2941 
- [x] #2965
- [x] #2968 
- [x] #2971 
- [x] #2973
- [ ] #2942 needs some help.
- [x] #2924

**Comment by shoyer** [comment]
Last call... this release has been dragging on for too long, so I want to issue it ASAP, likely after merging https://github.com/pydata/xarray/pull/3036.

I'm happy to do another follow-on release next week for anything that didn't make the cut.

**Comment by dcherian** [comment]
See #3038

**Comment by shoyer** [comment]
I'm just waiting on someone to take a look at the bug fix for dask/rolling windows in https://github.com/pydata/xarray/pull/3040

**Comment by shoyer** [comment]
OK, I merged #3040.

I'll probably issue the release tomorrow.

**Comment by shoyer** [comment]
See  https://github.com/pydata/xarray/pull/3060 for updated whats-new docs....

**Comment by shoyer** [comment]
done!
