### ISSUE TITLE
0.15.1 release

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#3869]
It'd be nice to issue a release by the end of March (two months since previous release)

Please edit this list as you wish.

**Must-have**
- [x] #3862 error when assigning to IndexVariable.values
- [x] #3840 delete index when deleting coordinate variable
- [x] #3874 un-xfail the tests from #3808 (https://github.com/pydata/xarray/issues/3751#issuecomment-599231986)
- [x] #3833, #3870 HTML repr with non-str keys fix (since it is now on by default)

**Nice to have**
- [ ] #3816 map_blocks template
- [ ] #3817 map_blocks new unindexed dimension
- [ ] #3818 map_blocks dask args
- [ ] #3847 assert_allclose diff
- [x] #3826 ellipsis in stack
- [x] #3836 where docstring
- [ ] some progress on #3868
- [ ] #3594 unit support
- [ ] #3871 idxmin, idxmax

**Comment by mathause** [comment]
- [ ] #3833 ? now that the repr is turned on by default 
- [ ] un-xfail the tests from #3808 (https://github.com/pydata/xarray/issues/3751#issuecomment-599231986)

**Comment by keewis** [comment]
if we release without #3594, we need to edit the existing `whats-new.rst` entry, otherwise we'd claim full support when it currently is partial at most

**Comment by max-sixty** [comment]
Shall we proceed? 

@keewis thoughts re #3594?

**Comment by keewis** [comment]
we can not include #3594 (which might justify a new major version?) but then I'd like to edit the entry in `whats-new.rst`

**Comment by max-sixty** [comment]
whatsnew fixups in https://github.com/pydata/xarray/pull/3879

**Comment by keewis** [comment]
do we also need to remove `Panel` from `pandas.rst`?

**Comment by max-sixty** [comment]
> do we also need to remove `Panel` from `pandas.rst`?

Good point, on it now

**Comment by max-sixty** [comment]
Shall we proceed?

**Comment by dcherian** [comment]
Ok by me.

**Comment by max-sixty** [comment]
Done! Will send out tweet & emails now! Thanks everyone!

**Comment by dcherian** [comment]
wow that was quick! Thanks @max-sixty

**Comment by max-sixty** [comment]
NB: I screwed up the list of names, there's something about copying from the command line to a Google Groups form; and only visible after sending. I added a note to https://github.com/pydata/xarray/pull/3882. 

https://groups.google.com/forum/#!topic/xarray/hK158wAviPs

I'll fix before sending to the other lists.
