### ISSUE TITLE
release v0.18.0

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#5232]
As discussed in the meeting, we should issue a release soon with the new backend refactor and the new docs theme.

Here's a list of blockers:
- [x] #5231
- [x] #5073
- [x] #5235

Would be nice and look done:
- [x] #5244 
- [x] #5258
- [x] #5101
- [x] ~#4866~ (we should let this sit on master for a while to find bugs)
- [x] #4902
- [x] ~#4972~ (this should probably also sit on master for a while)
- [x] #5227
- [x] #4740
- [x] #5149

Somewhat important, but no PR yet:
- [x] ~#5175~ (as pointed out by @shoyer, this is really a new feature, not a regression, it can wait)

@TomNicholas and @alexamici volunteered to handle this. I can be online at release time to help with things if needed. 

Release instructions are here: https://github.com/pydata/xarray/blob/master/HOW_TO_RELEASE.md

IIRC they'll need to be added to the PyPI list and RTD list.

**Comment by Illviljan** [comment]
May I suggest #4740, the only thing this needs I think is a rebase. I recently got a new computer and was reminded how slow the interpolation is without these changes.

**Comment by alexamici** [comment]
I propose to following timeline that is the fastest I can personally try:

- Monday May the 3rd, feature freeze, please refrain from merging new features unless they are discussed here
- during feature freeze everybody please help reviewing the PR in the list above
- Thursday the 6th, target release day, the best would be to schedule a window for a couple of hours (?) for @TomAugspurger and me to going through the release steps together with @dcherian.

@TomAugspurger and others does it work for you all?

**Comment by TomNicholas** [comment]
@alexamici I think you tagged the wrong Tom, but yes that works for me.

**Comment by max-sixty** [comment]
I think @alexamici 's plan is reasonable. I've had less of a process — no freeze etc — and that's worked fine — we do have a good test suite, and I've been really trying to make the release process a normal thing anyone can do in an hour. 

But it's your call (and there's not much practical difference).

Thanks again!

**Comment by dopplershift** [comment]
> We can avoid this by using the pypi github action thing to automatically build and upload when tagging a release on github. It uses a repo-level secret. Just a thought.

$0.02 from an outsider is that this has served us exceedingly well on MetPy. Our release process has become:
1. Close milestone
2. Adjust the auto-generated draft GitHub release (summary notes)
3. Click "publish release" -> packages uploaded to PyPI
4. Merge conda-forge update from their bots

It's almost *more* secure this way because the token from PyPI only has upload permissions--no need to store someone's password.

**Comment by TomNicholas** [comment]
(@dcherian I've signed up on RTD now)

**Comment by keewis** [comment]
great, you're a maintainer now (for `pint-xarray`, too, btw)

**Comment by dcherian** [comment]
It'd be nice to bump our minimum dependency versions if someone has the time.

**Comment by alexamici** [comment]
Form what I can see the #5258 "bump versions" looks ready, someone with knowledge about minimum versions please merge it.

After that is in, @dcherian you can probably uncomment the `var._meta` bit in #4740 "faster interp" and we can merge it as well. Again I'm not a user of that part of code, and I would feel more conformable if someone with more knowledge would click on the "merge" button.

This leaves only #5235 as a blocker that has a failing test, a proposed fix by @keewis, but the OP hasn't responded yet. How should we handle it?

**Comment by alexamici** [comment]
Any thoughts on merging #5244 and ding 0.18.0 release via GitHub Actions?

I'm using GA in a couple of repositories and I find them very handy, but I usually had to make a couple of releases before getting all the details right, which looks awkward to do with a high profile project like *xarray*.

We could try release one or more release candidates and go for `v0.18.0` only after we are sure the GA are clean up though.

Any thoughts?

**Comment by keewis** [comment]
we could also temporarily switch the uploads to `test.pypi.org` to verify, create debug versions (rc candidates?) and switch back to `pypi.org` once we're confident

**Comment by kmuehlbauer** [comment]
> we could also temporarily switch the uploads to `test.pypi.org`

Why not always upload pushes to master to `test.pypi.org`?

**Comment by keewis** [comment]
I think that's because nobody had that idea, yet.

**Comment by alexamici** [comment]
@TomNicholas & @dcherian I'm having a look at the what's new, shall we set a time for going through the release process? do we want do the steps while in a call?

**Comment by TomNicholas** [comment]
@alexamici yes sure - I'm free anytime today except for 2-3pm EST.

**Comment by alexamici** [comment]
@TomNicholas I'm in Europe, with a meeting on 17:30-18:30 CEST (11:30-12:30 EST) we can probably start now-ish and finish after 3pm EST. I propose to hijack the community meeting zoom :)

**Comment by dcherian** [comment]
We're still waiting on #5235.

Let's do 12.30 Eastern at https://columbiauniversity.zoom.us/j/953527251

**Comment by alexamici** [comment]
@dcherian 11:30-12:30 EST I'm meeting with Stephan and Joe, I hope to have them merge #5235 :)

12:30 EST is fine by me.

**Comment by keewis** [comment]
#5235 shouldn't be that much of an issue. There are two decisions to check: never collapse the `repr` of `MemoryCachedArray` and keep the array used to check that small (we have a limit of `1e5`, after which the `repr` changes from `array([...])` to `[xyz values with dtype=...]`)

**Comment by dcherian** [comment]
I don't have permissions to generate a PyPI token... I think either @jhamman or @shoyer need to do that.

**Comment by keewis** [comment]
uploading to TestPyPI works so uploading to PyPI *should* work, too, once we have the token

**Comment by alexamici** [comment]
@dcherian I'm sorry, I have cannot make it by 12:30 EST. I think you and @TomNicholas can go on without me or I will be back later.

**Comment by dcherian** [comment]
OK I think we can go ahead. 3 people is pretty overkill for the release process :P The token has been added and I'm in the Zoom room @TomNicholas

**Comment by dcherian** [comment]
Hmm... Looks like it built but didn't upload: https://github.com/pydata/xarray/runs/2520588073?check_suite_focus=true

cc @keewis  @andersy005

**Comment by andersy005** [comment]
> Hmm... Looks like it built but didn't upload: [pydata/xarray/runs/2520588073?check_suite_focus=true](https://github.com/pydata/xarray/runs/2520588073?check_suite_focus=true)
> 
> cc @keewis @andersy005

Sorry about that. I think the culprit here are the `if` conditions which evaluates to `false` on release events... @keewis what do you think? :) 

https://github.com/pydata/xarray/blob/01c1d25578634306b5d3179989a0a9bd867de176/.github/workflows/pypi-release.yaml#L66

https://github.com/pydata/xarray/blob/01c1d25578634306b5d3179989a0a9bd867de176/.github/workflows/pypi-release.yaml#L75

**Comment by alexamici** [comment]
@dcherian I0m back. I think the easiest is for you to upload the artefacts using with twine. If you need any help I'm in the zoom meeting.

**Comment by TomNicholas** [comment]
> I think the easiest is for you to upload the artefacts using with twine.

I guess I can't do this because I'm no one of the registered package owners on PyPI?

**Comment by andersy005** [comment]
Never mind... There's a bug in this `if`

https://github.com/pydata/xarray/blob/01c1d25578634306b5d3179989a0a9bd867de176/.github/workflows/pypi-release.yaml#L84

It should be `github.ref` instead of `github.event.ref`... Opening a PR shortly (not sure if you still want to use the GitHub action)...

**Comment by TomNicholas** [comment]
If we merge that PR and then I/someone clicks "New Release" again (and presumably calls it `v0.18.1`?) then that should just trigger the GitHub action again?

**Comment by dcherian** [comment]
@TomNicholas Sounds good to me; just edit whats-new again.

**Comment by TomNicholas** [comment]
Or @andersy005 suggested deleting the last tag and re-making it? Happy to try either (after the meeting I'm lurking in is done)

**Comment by alexamici** [comment]
Deleting and re-creating the release should work (I've done it on one of my projects)

**Comment by TomNicholas** [comment]
Okay let me try that then

**Comment by andersy005** [comment]
I accidentally closed this via Github's keywords... The bug in the CI workflow should be fixed.

**Comment by TomNicholas** [comment]
hmm should I also delete the tag? It appears to be also linked to one of @keewis ' PRs (#5272)

**Comment by andersy005** [comment]
> hmm should I also delete the tag? 

Yes...

**Comment by alexamici** [comment]
> hmm should I also delete the tag? It appears to be also linked to one of @keewis ' PRs (#5272)

yes, sorry: delete release AND tag. Then re-create release.

**Comment by andersy005** [comment]
@keewis, do we need to do something with the release on test.pypi.org?

**Comment by keewis** [comment]
errr... we can't do anything about that, PyPI and TestPyPI don't allow republishing the same version

**Comment by keewis** [comment]
maybe we should make the "upload to TestPyPI" a separate step?

**Comment by TomNicholas** [comment]
oh - I just deleted both and then re-released just now, but v0.18.0 again...

**Comment by TomNicholas** [comment]
Looks like it did push to PyPI this time though? https://github.com/pydata/xarray/runs/2521179293?check_suite_focus=true

**Comment by dcherian** [comment]
Yup, nice work everyone!

https://pypi.org/project/xarray/

**Comment by keewis** [comment]
ah, right, only the "upload tag" workflow run failed

**Comment by alexamici** [comment]
I'm testing after `pip install -U xarray` just to be on the safe side 😄

**Comment by TomNicholas** [comment]
Alright I'll carry on with the other steps then I guess? :sweat_smile:

**Comment by TomNicholas** [comment]
How many xarray devs does it take to do a release? Answer: at least 5 apparently

**Comment by alexamici** [comment]
> How many xarray devs does it take to do a release? Answer: at least 5 apparently

🤦 

But next time it will be sooooooo smooth!

**Comment by andersy005** [comment]
> maybe we should make the "upload to TestPyPI" a separate step?

Or we could just set

```yaml
skip_existing: true
```

on the upload to TestPyPI step.

**Comment by TomNicholas** [comment]
Okay that should be everything except emailing the mailing lists, which I will try now

**Comment by alexamici** [comment]
`12899 passed, 1145 skipped, 211 xfailed, 63 xpassed, 321 warnings` on my Mac.

**Comment by alexamici** [comment]
@TomNicholas feel free to close the issue once you are done.

**Comment by TomNicholas** [comment]
My email got bounced from pyaos@lists.johnny-lin.com because I'm not a member, but otherwise I think this is done. (I'm also not subscribed to numpy-discussion@scipy.org or scipy-user@scipy.org so maybe it's about to get bounced from there too).

**Comment by TomNicholas** [comment]
I updated the release guide in #5274 by the way.

**Comment by dcherian** [comment]
Nice work, @TomNicholas

**Comment by shoyer** [comment]
Thanks everyone, great work!
