### ISSUE TITLE
0.18.1 patch release?

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#5298]
I think we should issue a patch release soon.

- [x] `xarray.map_blocks` will break with new dask,distributed releases this week since we don't have a released version with https://github.com/pydata/xarray/pull/5271
- [x] #5296: fix for regression reported in #5295 
- [x] #5300: fix the error message in #5291 so that it is more helpful. It's a key entry point for new users.
- [x] #5299 RTD build is broken
- [ ]  #5329 should throw `FileNotFoundError` error on nonexistent file?

Nice to have
- [ ] #5252 zarr region
- [ ] #5045 assigning to subset
- [x] #5239 drop_duplicates
- [x] #5288 invalid reference date error

Thoughts? Volunteers?

**Comment by shoyer** [comment]
I'm going to take a look into fixing #5291

**Comment by shoyer** [comment]
I'd also love to get https://github.com/pydata/xarray/pull/5252 in (it makes `to_zarr()` with `region` much faster / more efficient), but it's not really urgent.

**Comment by max-sixty** [comment]
I can "do the release" if that's helpful

**Comment by keewis** [comment]
I can also help with the release.

**Comment by dcherian** [comment]
shall we merge #5300 and release? Users are running in to the map_blocks issue, see #5331

**Comment by max-sixty** [comment]
This is done. I'll send an email & check the docs are working tomorrow. Let me know anything I missed!

**Comment by shoyer** [comment]
thanks Max!

We can always do a 0.18.2 for https://github.com/pydata/xarray/issues/5329 if need be :)

**Comment by dcherian** [comment]
Thanks Max! Looks like that went pretty smoothly!

**Comment by max-sixty** [comment]
From https://github.com/pydata/xarray/pull/4753#issuecomment-841894087

> I wonder if we should hold off on merging until after the 0.18.1 release -- or maybe just move to a date based versioning system / release cycle like dask.

I am keen on whatever lets us release faster and easier — very open to a set schedule.

Releasing has got to a place such that increasing the frequency isn't that costly. The recent work by @andersy005 and others to automate PyPI has made that even more so. There are some smaller tasks we can put into pipelines if we want to squeeze more out there (e.g. updating stable branch, adding contributor lists). The only really necessary tasks are writing the summary, organizing the whatsnew, sending out communications.

There's an extreme end of "constantly release new main branches". I don't see anything functionally wrong with that on, but I'm sure there are unexplored consequences, and I'm not sure our role is to forge a new path in OSS release cycles.

So maybe monthly is a reasonable balance?

**Comment by andersy005** [comment]
Glad to hear that releasing is getting easier/simpler :) 

> There are some smaller tasks we can put into pipelines if we want to squeeze more out there (e.g. updating stable branch, adding contributor lists). The only really necessary tasks are writing the summary, organizing the whatsnew, sending out communications. 

I've been thinking about this, and I'm wondering if something like this great tool: [github-activity](https://github-activity.readthedocs.io/en/latest/) could help us (at least with updating `whatsnew.rst`). `github-activity` is able to generate the changelog from the GitHub API. This would eliminate the need for updating whatsnew.rst multiple times (once for each PR). With proper labels, `github-activity` is able to categorize PRs and Issues during the changelog generation. Another cool feature of `github-activity` is that it includes other contributions in addition to the default PR submissions: https://github-activity.readthedocs.io/en/latest/#how-does-this-tool-define-contributions-in-the-reports

> There's an extreme end of "constantly release new main branches". I don't see anything functionally wrong with that, but I'm sure there are unexplored consequences, and I'm not sure our role is to forge a new path in OSS release cycles.

I'm curious.. How are these "new main branches" different from git tags from releases? 

> So maybe monthly is a reasonable balance?

👍🏽 for frequent/monthly release cadence

**Comment by andersy005** [comment]
Here's one example that shows `github-activity` in action: https://jupyterbook.org/reference/_changelog.html

**Comment by max-sixty** [comment]
> I'm curious.. How are these "new main branches" different from git tags from releases?

I had meant commit rather than branch — i.e. "on every commit to master". But as a thought experiment rather than a proposal
