### ISSUE TITLE
Datatree design discussions - weekly meeting

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#8747]
### What is your issue?

In the [bi-weekly dev meeting](https://github.com/pydata/xarray/issues/4001) today we agreed that deliberate higher-level discussions of datatree's design would be useful. (i.e. we're not worried about our ability to write high-quality code, so let's focus review time more explicitly on the high-level design questions.)

This could take the form of me just talking through what I did in a certain part of the code and why, or a targeted discussion on specific design questions that I was never quite sure about. Some examples of the latter, as food for thought:
- [ ] Inheritance of dimension coordinates from parent nodes? https://github.com/xarray-contrib/datatree/issues/297
- [x] ~~Symbolic links? https://github.com/xarray-contrib/datatree/issues/5~~ (we decided this was overkill)
- [ ] Is `dt.ds` ugly? See also the difference between `dt.ds` and `dt.to_dataset()` https://github.com/xarray-contrib/datatree/issues/303#issuecomment-1917798769
- [ ] Which methods should map over the subtree and which shouldn't? (can't find the issue for this one)
- [ ] Ignore missing dims when mapping over subtree? https://github.com/xarray-contrib/datatree/issues/67
- [ ] API for sub-tree selection https://github.com/xarray-contrib/datatree/issues/254
- [ ] API for merging leaves https://github.com/xarray-contrib/datatree/issues/192
- [ ] Dict-like interface ambiguities https://github.com/xarray-contrib/datatree/issues/240
- [ ] The tree broadcasting rabbit hole https://github.com/xarray-contrib/datatree/issues/199
- [ ] Relationship between datatree and catalogs https://github.com/xarray-contrib/datatree/issues/134
- [ ] Should `xr.concat`/`xr.merge` accept `DataTree` objects? (and map over them by default?) https://github.com/pydata/xarray/issues/9106

There was also this [design doc](https://docs.google.com/document/d/19jVW5lL2jwhS0dgj9XqPBrcvIa13cpWrnDsnVLqZkfc/edit?usp=sharing) I wrote at one point

@flamingbear are you free at 11:30am EST on Tuesday each week? @shoyer, @keewis and I are all free then. Others also welcome (e.g. @owenlittlejohns , @eni-awowale, @etienneschalk), but not required :)

**Comment by flamingbear** [comment]
@TomNicholas Yes, I'm good on 11:30am EST Every Tuesday.

**Comment by eni-awowale** [comment]
Thanks for putting this together @TomNicholas! 11:30 EST on Tuesdays should generally work for me.

**Comment by flamingbear** [comment]
> [Google calendar event link](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=N3N0NHF2b3JwcjVzc2dxZTJtN25yMTIxbmZfMjAyNDAyMjBUMTYzMDAwWiB0b21AY3dvcnRoeS5vcmc&tmsrc=tom%40cworthy.org&scp=ALL) (There is an xarray calendar but I don't think I have access to it)
FYI I can't open this calendar link.

**Comment by TomNicholas** [comment]
> FYI I can't open this calendar link.

Ugh - I tried changing the account which owns the event, but if that still doesn't work then just forget about it. I'll post here if we need to cancel or change the time or anything.

**Comment by TomNicholas** [comment]
@shoyer @owenlittlejohns @keewis @flamingbear the original issue about storing `xr.Variable` objects rather than `xr.Dataset` objects is here: https://github.com/xarray-contrib/datatree/issues/2#issuecomment-924217495. My actually reasoning is recorded in this comment https://github.com/xarray-contrib/datatree/issues/2#issuecomment-924233090, but this is not set in stone!

**Comment by TomNicholas** [comment]
I can't make the normal time of 11:30am EST tomorrow (it clashes with a job talk I need to attend).

The only other time tomorrow I could do is 1 hour earlier (10:30am EST). I'll be on zoom then anyway in case anyone shows up!

@shoyer @flamingbear @eni-awowale @owenlittlejohns

**Comment by schlich** [comment]
I'd like to pop in and be a fly on the wall of these meetings if they're still happening... lmk

**Comment by TomNicholas** [comment]
@schlich yes they are still happening! You missed one yesterday in fact. You're welcome to pop in.

**Comment by schlich** [comment]
Wonderful, it's in my calendar

**Comment by TomNicholas** [comment]
Now that we've released DataTree in xarray `v2024.10.0`, I'm going to cease these meetings, in favour of the normal bi-weekly xarray meetings (https://github.com/pydata/xarray/issues/4001). Anyone is still welcome to those, and we can discuss DataTree issues there!
