### ISSUE TITLE
TODO: release v0.8.0

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#910]
I've been putting this off long enough -- we need to get all the recent work on xarray out there!

Things I'd like to merge first:

- [x] xarray.merge function and major refactor for merge logic #857
- [x] Fix issue with expand_dims on 0d arrays of tuples #867
- [x] Refer users to Stack Overflow for support in the docs #922

Given the scope of these internal changes (especially #857), possibly a release candidate would be in order?
